name: 06- Context
run-name: 06- Context | DEBUG- ${{ inputs.debug }}

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "job"
      MY_Override_VAR: "job"

    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{github.ref}}"
          echo "SHA: ${{github.sha}}"
          echo "Actor: ${{github.actor}}"
          echo "Workflow: ${{github.workflow}}"
          echo "Action: ${{github.action}}"
          echo "Event Path: ${{github.event_path}}"
          echo "Workspace: ${{github.workspace}}"
      - name: Retrieve Variables
        run: |
          echo "variable value: ${{vars.MY_VAR}}"
          - name : Display Environment Variables
            run: |
              echo "Job env: ${{env.MY_JOB_VAR}}"
              echo "Overwritten env: ${{env.MY_Override_VAR}}"
