name: 07- Using Expression
run-name: 07- Using expression | DEBUG- ${{ inputs.debug && 'ON' || 'OFF' }}

env:
  MY_VAR_With_DEFAULT: ${{ vars.MY_VAR || 'default_value' }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: "[Debug] Print start-up"
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{github.ref}}"
          echo "SHA: ${{github.sha}}"
          echo "Actor: ${{github.actor}}"
          echo "Workflow: ${{github.workflow}}"
          echo "Action: ${{github.action}}"
          echo "Event Path: ${{github.event_path}}"
          echo "Runner Os: ${{runner.os}}"
      - name: "[Debug] Print when triggered from main"
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: |
          echo "I was triggered from main branch"
      - name: Greetings
        run: echo "Hello world"
