name: 10- Using inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "skip the actual deployment and only print the build output"
        default: false
      target:
        type: environment
        description: "target environment"
        required: true
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        description: "tag to deploy"
        default: v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build steps
        run: echo "Building the project from tag ${{ inputs.tag }}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: echo "Building the project from tag ${{ inputs.target }}"
