name: 14- working with artifacts

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        description: "whether to execute cache step"
        default: true
      node-version:
        description: "Node version"
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.event.inputs.node-version }}
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ github.event.inputs.use-cache }}
        id: cache-node-modules
        with:
          path: 14-artifacts/react-app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: upload build files
        uses: actions/upload-artifact@v2
        with:
          name: react-app
          path: 14-artifacts/react-app/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: react-app
          path: build
      - name: show folder structure
        run: ls -R
